# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Program Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
        branch: 'test'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3

      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Generate sintetic data
      run : |
        sudo apt update
        sudo snap install blender --classic
        unzip test.zip
        blender -b test.blend -o vid.avi  -a
        ls .
    - name: extract frames
      run: |
        mkdir frames
        python main.py -i vid.avi -s 30 -f 1
        cat log.csv | sed 's/,/ ,/g' | column -t -s,
        
        
    
#    - name: Test with pytest
#      run: |
#        pytest
